FW_READY=1
EGPRS_SUPPORT=0
SUPPORTED_RAT=105
IS_CTC=0
VOLTE_911_CALL=0
CA_ENABLED=0
LTE_CS_CAPA=0
MSIM_SUBMODE=0
SUPPORTED_NRCA=1
SUPPORT_LTE_CAPA_OPTION_C=1
REJECT_INFO_FOR_SIM_TRANSFER=0
WFC_DEFAULT_SPN=
SUPPORT_UAC_TYPE=2
